# Generated by Django 4.1.1 on 2022-09-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_created=True, auto_now=True)),
                ('anterior', models.IntegerField(verbose_name='Leitura Anterior')),
                ('atual', models.IntegerField(verbose_name='Leitura Atual')),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feira.bancas')),
            ],
        ),
    ]
