# Generated by Django 4.1.1 on 2022-09-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancas',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Número'),
        ),
    ]
