# Generated by Django 4.1.1 on 2022-09-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feira', '0002_alter_bancas_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancas',
            name='qtd',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
