# Generated by Django 4.1.1 on 2022-09-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feira', '0003_bancas_qtd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancas',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='leitura',
            options={'ordering': ['banca']},
        ),
        migrations.AlterField(
            model_name='bancas',
            name='qtd',
            field=models.IntegerField(default=1),
        ),
    ]
