# Generated by Django 4.1.1 on 2022-10-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feira', '0007_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.FloatField(max_length=10, verbose_name='Conta total')),
                ('kwh', models.FloatField(blank=True, max_length=5, null=True, verbose_name='Kw/h')),
                ('taxaIlum', models.FloatField(max_length=5, verbose_name='Tx iluminação Pública')),
                ('corredor', models.FloatField(max_length=5, verbose_name='Iluminação dos Corredores')),
            ],
        ),
        migrations.DeleteModel(
            name='Conta',
        ),
    ]
