# Generated by Django 4.1.1 on 2022-09-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banca2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banca', models.CharField(choices=[('1', '590/611'), ('2', '591 '), ('3', '592/594'), ('4', '593'), ('5', '595'), ('6', '596/605'), ('7', '597'), ('8', '598'), ('9', '599'), ('10', '600'), ('11', '601/603'), ('12', '602'), ('13', '604'), ('14', '606'), ('15', '607'), ('16', '608'), ('17', '609'), ('18', '612/610/640/641'), ('19', '613/615'), ('20', '614/616'), ('21', '618/637'), ('22', '626/633'), ('23', '628'), ('24', '630'), ('25', '631'), ('26', '632'), ('27', '635'), ('28', '636'), ('29', '638/639'), ('30', '642'), ('31', '643'), ('32', '644'), ('33', '645'), ('34', '646')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Leitura2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_created=True, auto_now=True)),
                ('anterior', models.IntegerField(verbose_name='Leitura anterior')),
                ('atual', models.IntegerField(verbose_name='Leitura atualr')),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feira2.banca2')),
            ],
        ),
    ]
