# Generated by Django 4.1.1 on 2022-09-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feira2', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
