# Generated by Django 4.1.1 on 2022-10-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feira2', '0004_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitura2',
            name='banca',
        ),
    ]
