# Generated by Django 4.1.1 on 2022-10-12 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feira', '0006_alter_bancas_obs'),
        ('feira2', '0005_remove_leitura2_banca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('bancas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feira.bancas')),
            ],
            bases=('feira.bancas',),
        ),
        migrations.AddField(
            model_name='leitura2',
            name='banca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='feira2.banca'),
            preserve_default=False,
        ),
    ]
