# Generated by Django 4.1.1 on 2022-10-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feira2', '0006_banca_leitura2_banca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura2',
            name='banca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feira2.banca'),
        ),
    ]
